apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: "rc1a-jht0d619sr0rm739.mdb.yandexcloud.net"
            - name: PMA_PORT
              value: "3306"
            - name: PMA_PMADB
              value: "netology_db"
            - name: PMA_USER
              value: "dbuser"
            - name: PMA_PASSWORD
              value: "Password123"

---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - name: http
    port: 80
    targetPort: 80

